version: '3.1'

services:
  svern-app:
    image: svern
    container_name: svern-app
    restart: always
    ports:
      - 49157:3000
    environment:
      MONGO_HOST: svern-db
      MONGO_USER: ${MONGO_USER}
      MONGO_PW: ${MONGO_PW}
  svern-db:
    image: mongo
    container_name: svern-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
