version: '3.1'

services:
  svern-app:
    image: svern-app
    container_name: svern-app
    restart: always
    ports:
      - 49157:3000
    environment:
      REDIS_HOST: svern-db
      REDIS_PW: ${REDIS_PW}
  svern-db:
    image: redis:bullseye
    container_name: svern-db
    restart: always
    command: redis-server --requirepass ${REDIS_PW}
